### PR TITLE
Add support for blade directives and component aliases

### PR DESCRIPTION
**Pull request by shovhan**
This pull request add support for directives and component aliases.
It is now possible to use `Blade::component('view.name', 'component')` and `Blade::directive('name', function () {})` with 'htmlmin.blade' config set to `true`.

### CODE REVIEW

**Comment by johannitsa** [comment]
@srmklive can you merge this, please?

**Comment by shovhan** [comment]
When using Laravel 7 components with the `htmlmin.blade` configuration set to true, a 'Unable to locate a class or view for component <some-component-name>' error may occur

Last сommit (d8e9749) solves this error

**Comment by u01jmg3** [comment]
@shovhan

https://github.com/HTMLMin/Laravel-HTMLMin/blob/e67fe976e3fd1e92568341ce84f338fa4c0ffc47/src/HTMLMinServiceProvider.php#L165-L170

I am getting the following error from Laravel when running `php artisan package:discover --ansi` due to the code above. It is caused by 0aca66d.

```
In Container.php line 811:
  Target class [view] does not exist.

In Container.php line 809:
  Class view does not exist
```

**Comment by u01jmg3** [comment]
The yet unmerged PR #162 looks to fix this

**Pull request merged**
