### PR TITLE
Update to Laravel 5.6

### PR DESCRIPTION
**Pull request by rodrigopedra**
Add Laravel 5.6 support, readme and travis were updated.

### CODE REVIEW

**Comment by rodrigopedra** [comment]
I realize PR #106 does the same thing, but I heavily use this package and want to upgrade some of my projects to Laravel 5.6. If the previous PR fixes what you commented out in that PR please merge any of them.

Thanks!

**Comment by diego-vieira** [comment]
Can someone merge this, please?
Thanks

**Comment by rodrigopedra** [comment]
ping @GrahamCampbell  and @srmklive , please review this PR

**Comment by rodrigopedra** [comment]
Thanks for the merge!

Is it possible to tag a release?

**Pull request merged**
