### PR TITLE
Add Laravel 5.8 support

### PR DESCRIPTION
**Pull request by mul14**
This old PR is also related https://github.com/HTMLMin/Laravel-HTMLMin/pull/122

### CODE REVIEW

**Comment by globalmac** [comment]
+1

**Comment by mul14** [comment]
Instead of `5.1|5.2|5.3 ...` We might change to `^5.1`. All next Laravel version should compatible with this library. Except, when something breaks in new Laravel version, then we could add `^5.1,<5.9`.

**Comment by globalmac** [comment]
ping @srmklive

**Comment by bramburn** [comment]
What anyone checked if this has been affected by the 5.7 to 5.8 version? no point just changing package versions.

see link [https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0](https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0)

**Comment by srmklive** [comment]
Tagged new release for Laravel 5.8

**Pull request closed without merging**
