### PR TITLE
Update BladeMinifier.php

### PR DESCRIPTION
**Pull request by strekozlik**
BladeMinifier add replace rule. Please approve the addition of this rule. This rule will help remove all unnecessary blank spaces from the template!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
`ErrorException: preg_replace(): Unknown modifier 'g'`

**Comment by strekozlik** [comment]
Please, see how time will be

**Comment by KristofMorva** [comment]
First of all, I think it should be ` +?`, not ` *?`, as it'll cause unnecessary replaces. But more importantly, it will also cause some unexpected behavior. Imagine the following scenario:
```
<i class="fa fa-circle"></i> <span>Time</span>
```
Everyone would expect some spacing between the two elements, with this regex it would disappear.

**Comment by GrahamCampbell** [comment]
Yes, I don't think this replacement is safe to make. For a more thourgh minification, you can use our minification middleware that runs on the rendered output.

**Comment by strekozlik** [comment]
Make it up like this 

`<i class="fa fa-circle"></i> <span>Time</span>`

not properly.
To get the result you need, replace all the necessary spaces with

`&nbsp`
`<i class="fa fa-circle"></i>&nbsp<span>Time</span>`

and will, then what do you want.

With the correct approach to layout, there is absolutely no need for any uncontrolled blank.

Minification at the output requires more resources and you yourself write that it does not fit the product.

What is the point of minimizing the views of the blade?
After all, you can immediately remove everything that is not necessary and enjoy the correct and controlled views.

**Comment by KristofMorva** [comment]
I'm pretty sure non-breaking space is not a good solution for this problem, it's not comfortable. And actually at the end you'll lose more characters than you get. `&nbsp;` is the correct syntax, and it takes 6 spaces. By using this solution, we'd gain nothing, but making the code more disgusting.

**Pull request closed without merging**
